services:
    backend:
        build:
          context: .
        volumes:
          - ./app:/usr/src/server/app

        privileged: true
        cap_add:
          - NET_ADMIN # This specifically adds the NET_ADMIN capability to your container
        ports:
          - "8000:8000"